# 线性代数

```{note}
回顾一下基本线性代数运算的Pytorch实现。
```

## 向量

In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
len(x)

4

In [3]:
# 点积
y = torch.ones(4, dtype=torch.float32)
torch.dot(x, y)

tensor(6.)

In [4]:
# 先按元素乘，再求和
torch.sum(x * y)

tensor(6.)

In [5]:
# l2范数
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [6]:
# l1范数
torch.abs(u).sum()

tensor(7.)

## 矩阵

In [7]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
# 矩阵转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# 通过分配新内存，将A的⼀个副本分配给B
B = A.clone()
A + B

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [10]:
# Frobenius范数
torch.norm(torch.ones((4, 9)))

tensor(6.)

### 矩阵乘法

In [11]:
# 两个矩阵按元素乘
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [12]:
# 矩阵和向量乘法
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [13]:
# 两个矩阵的乘法
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 高阶张量

In [14]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
# 标量和张量的乘积
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a * X

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

## 降维

In [16]:
A.shape

torch.Size([5, 4])

In [17]:
# 沿着行求和
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [18]:
# 沿着列求和
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [19]:
# 沿着行、列求和
A.sum(axis=[0, 1])

tensor(190.)

In [20]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [21]:
# 累计和必须指定axis
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

### 保持维度不变

In [22]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 torch.Size([5, 1]))

In [23]:
# 保持维度后可以广播
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])