# Tensor

```{note}
首先，我们介绍n维数组，也称为张量（tensor），它类似于Numpy的ndarray。<br/>
但深度学习框架相比Numpy多了一些重要功能：1.支持GPU加速；2.支持自动微分。
```

## 创建张量

In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
# 元素的个数
x.numel()

12

In [5]:
# reshape类似于view
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
# 元素服从标准正态分布
torch.randn(3, 4)

tensor([[-0.7746,  0.5595,  0.5405,  0.2108],
        [ 0.2794,  0.3901, -0.1604, -0.5545],
        [ 0.4017,  1.2047,  0.1967,  0.6885]])

In [9]:
# 使用Python列表创建
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算

In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
# **是求幂运算符
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [11]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2.0, 1, 4, 3], [4, 3, 2, 1], [1, 2, 3, 4]])
# dim=0沿行连结，dim=1沿列连结
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 4.,  3.,  2.,  1.],
         [ 1.,  2.,  3.,  4.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  3.,  2.,  1.],
         [ 8.,  9., 10., 11.,  1.,  2.,  3.,  4.]]))

In [13]:
X == Y

tensor([[False,  True, False,  True],
        [ True, False, False, False],
        [False, False, False, False]])

In [14]:
# 产⽣⼀个单元素张量
X.sum()

tensor(66.)

## 广播机制

类似于Numpy

In [15]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

In [17]:
X[-1], X[1: 3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
X[0:2, :] = 11
X

tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [ 8.,  9., 10., 11.]])

## 节省内存

In [20]:
# 分配新内存
before = id(Y)
Y = Y + X
id(Y) == before

False

In [21]:
# 原地操作
before = id(X)
X += Y
id(X) == before

True

In [22]:
# 使用[:]进行赋值不会分配新内存
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
Z[:] = X + Y
print("id(Z):", id(Z))

id(Z): 140724812756672
id(Z): 140724812756672


## 转换为其他Python对象

In [23]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [24]:
# 使用.item()获得元素
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)